import csv

# Os dados estão em ordem por dia, são cinco dados de cada dia por vez
# Por ex. é S S S S S -> T T T T T
#           1 2 3 4 5    1 2 3 4 5

data = [
    {'dia': 'Seg', 'linha': 1, 'requests': 1504},
    {'dia': 'Seg', 'linha': 2, 'requests': 2025},
    {'dia': 'Seg', 'linha': 3, 'requests': 720},
    {'dia': 'Seg', 'linha': 4, 'requests': 803},
    {'dia': 'Seg', 'linha': 5, 'requests': 102},  
    {'dia': 'Ter', 'linha': 1, 'requests': 3032},
    {'dia': 'Ter', 'linha': 2, 'requests': 2001},
    {'dia': 'Ter', 'linha': 3, 'requests': 1006},
    {'dia': 'Ter', 'linha': 4, 'requests': 804},
    {'dia': 'Ter', 'linha': 5, 'requests': 225},   
    {'dia': 'Qua', 'linha': 1, 'requests': 1347},
    {'dia': 'Qua', 'linha': 2, 'requests': 2200},
    {'dia': 'Qua', 'linha': 3, 'requests': 1598},
    {'dia': 'Qua', 'linha': 4, 'requests': 703},
    {'dia': 'Qua', 'linha': 5, 'requests': 517},   
    {'dia': 'Qui', 'linha': 1, 'requests': 1578},
    {'dia': 'Qui', 'linha': 2, 'requests': 1794},
    {'dia': 'Qui', 'linha': 3, 'requests': 914},
    {'dia': 'Qui', 'linha': 4, 'requests': 912},
    {'dia': 'Qui', 'linha': 5, 'requests': 129},   
    {'dia': 'Sex', 'linha': 1, 'requests': 1754},
    {'dia': 'Sex', 'linha': 2, 'requests': 2685},
    {'dia': 'Sex', 'linha': 3, 'requests': 1234},
    {'dia': 'Sex', 'linha': 4, 'requests': 1003},
    {'dia': 'Sex', 'linha': 5, 'requests': 1017},   
    {'dia': 'Sab', 'linha': 1, 'requests': 298},
    {'dia': 'Sab', 'linha': 2, 'requests': 509},
    {'dia': 'Sab', 'linha': 3, 'requests': 1065},
    {'dia': 'Sab', 'linha': 4, 'requests': 1236},
    {'dia': 'Sab', 'linha': 5, 'requests': 1064},   
    {'dia': 'Dom', 'linha': 1, 'requests': 312},
    {'dia': 'Dom', 'linha': 2, 'requests': 34},
    {'dia': 'Dom', 'linha': 3, 'requests': 429},
    {'dia': 'Dom', 'linha': 4, 'requests': 137},
    {'dia': 'Dom', 'linha': 5, 'requests': 38},   
    {'dia': 'Seg', 'linha': 1, 'requests': 1456},
    {'dia': 'Seg', 'linha': 2, 'requests': 2239},
    {'dia': 'Seg', 'linha': 3, 'requests': 840},
    {'dia': 'Seg', 'linha': 4, 'requests': 801},
    {'dia': 'Seg', 'linha': 5, 'requests': 154},   
    {'dia': 'Ter', 'linha': 1, 'requests': 2819},
    {'dia': 'Ter', 'linha': 2, 'requests': 2293},
    {'dia': 'Ter', 'linha': 3, 'requests': 1102},
    {'dia': 'Ter', 'linha': 4, 'requests': 729},
    {'dia': 'Ter', 'linha': 5, 'requests': 304},    
    {'dia': 'Qua', 'linha': 1, 'requests': 1284},
    {'dia': 'Qua', 'linha': 2, 'requests': 2578},
    {'dia': 'Qua', 'linha': 3, 'requests': 1417},
    {'dia': 'Qua', 'linha': 4, 'requests': 728},
    {'dia': 'Qua', 'linha': 5, 'requests': 612},  
    {'dia': 'Qui', 'linha': 1, 'requests': 1417},
    {'dia': 'Qui', 'linha': 2, 'requests': 1912},
    {'dia': 'Qui', 'linha': 3, 'requests': 907},
    {'dia': 'Qui', 'linha': 4, 'requests': 953},
    {'dia': 'Qui', 'linha': 5, 'requests': 237},    
    {'dia': 'Sex', 'linha': 1, 'requests': 1418},
    {'dia': 'Sex', 'linha': 2, 'requests': 2481},
    {'dia': 'Sex', 'linha': 3, 'requests': 1237},
    {'dia': 'Sex', 'linha': 4, 'requests': 914},
    {'dia': 'Sex', 'linha': 5, 'requests': 1217},
    {'dia': 'Sab', 'linha': 1, 'requests': 415},
    {'dia': 'Sab', 'linha': 2, 'requests': 901},
    {'dia': 'Sab', 'linha': 3, 'requests': 1013},
    {'dia': 'Sab', 'linha': 4, 'requests': 1117},
    {'dia': 'Sab', 'linha': 5, 'requests': 917},
    {'dia': 'Dom', 'linha': 1, 'requests': 102},
    {'dia': 'Dom', 'linha': 2, 'requests': 117},
    {'dia': 'Dom', 'linha': 3, 'requests': 707},
    {'dia': 'Dom', 'linha': 4, 'requests': 229},
    {'dia': 'Dom', 'linha': 5, 'requests': 57},
]

with open('dados_onibus.csv', 'w', newline='') as csvfile:
    fieldnames = ['dia', 'linha', 'requests']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data)
